import { useState } from 'react';
import { SUGGESTED_TICKERS } from '../services/fmpService.js';

export default function TickerSelector({ onSelect }) {
  const [input, setInput] = useState('');
  const [error, setError] = useState('');

  const handleManualSubmit = () => {
    const ticker = input.trim().toUpperCase();
    if (!ticker) { setError('Please enter a ticker symbol'); return; }
    if (!/^[A-Z]{1,5}$/.test(ticker)) { setError('Enter a valid US ticker (1-5 letters)'); return; }
    setError('');
    onSelect(ticker);
  };

  const handleKeyDown = (e) => {
    if (e.key === 'Enter') handleManualSubmit();
  };

  return (
    <div style={{ maxWidth: 800, margin: '40px auto' }}>
      <div style={{ marginBottom: 40 }}>
        <div style={{ fontSize: 11, letterSpacing: 4, color: '#555', marginBottom: 8 }}>EQUITY ANALYSIS PLATFORM</div>
        <div style={{ fontSize: 22, fontWeight: 700, marginBottom: 8 }}>Analyze any US public company</div>
        <div style={{ color: '#666', fontSize: 13 }}>Enter any ticker or select from the suggestions below</div>
      </div>

      {/* Free text input */}
      <div style={{ display: 'flex', gap: 12, marginBottom: 40 }}>
        <input
          type="text"
          value={input}
          onChange={e => setInput(e.target.value.toUpperCase())}
          onKeyDown={handleKeyDown}
          placeholder="Enter ticker — e.g. AAPL, NVDA, TSLA"
          maxLength={5}
          style={{
            flex: 1,
            background: '#111',
            border: '1px solid #333',
            color: '#f0f0f0',
            padding: '14px 16px',
            fontSize: 16,
            fontFamily: 'inherit',
            letterSpacing: 2,
            outline: 'none',
          }}
        />
        <button
          onClick={handleManualSubmit}
          style={{
            background: '#f0f0f0',
            color: '#0a0a0a',
            border: 'none',
            padding: '14px 28px',
            cursor: 'pointer',
            fontSize: 12,
            letterSpacing: 3,
            fontFamily: 'inherit',
            fontWeight: 700,
          }}
        >
          ANALYZE →
        </button>
      </div>

      {error && (
        <div style={{ color: '#ff4444', fontSize: 12, marginBottom: 16, marginTop: -32 }}>{error}</div>
      )}

      {/* Suggested tickers */}
      <div style={{ fontSize: 11, letterSpacing: 3, color: '#555', marginBottom: 16 }}>QUICK SELECT</div>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(5, 1fr)', gap: 8 }}>
        {SUGGESTED_TICKERS.map(({ ticker, name, sector }) => (
          <button
            key={ticker}
            onClick={() => onSelect(ticker)}
            style={{
              background: 'none',
              border: '1px solid #222',
              color: '#f0f0f0',
              padding: '14px 12px',
              cursor: 'pointer',
              textAlign: 'left',
              fontFamily: 'inherit',
            }}
            onMouseEnter={e => e.currentTarget.style.borderColor = '#555'}
            onMouseLeave={e => e.currentTarget.style.borderColor = '#222'}
          >
            <div style={{ fontSize: 16, fontWeight: 700, marginBottom: 2 }}>{ticker}</div>
            <div style={{ fontSize: 11, color: '#666' }}>{name}</div>
          </button>
        ))}
      </div>

      <div style={{ marginTop: 32, padding: '16px', background: '#0a0a0a', border: '1px solid #1a1a1a' }}>
        <div style={{ fontSize: 11, color: '#555', lineHeight: 1.6 }}>
          Analysis uses real financial data from SEC filings and public financial databases.
          Results are generated by AI and are for informational purposes only — not financial advice.
        </div>
      </div>
    </div>
  );
}
